global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # API Server
  - job_name: 'apps'
    static_configs:
      - targets: ['apps:8001']