name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_PATH: /root/77maStI-playground/Swisstination

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy Monitoring to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Navigate to deployment directory
            cd ${{ env.DEPLOY_PATH }}
            
            # Create monitoring directory if it doesn't exist
            mkdir -p monitoring
            cd monitoring
            
            # Create environment file for the application
            cat > .env <<EOF
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            
            # Grafana Configuration
            GF_SECURITY_ADMIN_USER=admin
            GF_SECURITY_ADMIN_PASSWORD=admin123
            GF_USERS_ALLOW_SIGN_UP=false
            GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
            EOF
            
            # Set proper permissions for env file
            chmod 600 .env
            
            # Create directory structure for monitoring
            mkdir -p monitor/grafana/datasources
            mkdir -p monitor-source
            
            # Pull monitoring configuration files
            curl -o docker-compose.yml https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/docker-compose.yml
            
            # Download and verify Prometheus configuration
            curl -o monitor/prometheus.yml https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor/prometheus.yml
            
            # Verify the file was downloaded correctly
            if [ ! -f "monitor/prometheus.yml" ]; then
              echo "Error: prometheus.yml not found, creating default config"
              cat > monitor/prometheus.yml <<EOF
            global:
              scrape_interval: 15s
            
            scrape_configs:
              - job_name: 'prometheus'
                static_configs:
                  - targets: ['prometheus:9090']
            
              - job_name: 'apps'
                static_configs:
                  - targets: ['apps:8001']
            EOF
            fi
            
            # Pull monitor-source files
            curl -o monitor-source/collector.py https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor-source/collector.py
            curl -o monitor-source/metrics.py https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor-source/metrics.py
            
            # Pull grafana datasource configuration
            curl -o monitor/grafana/datasources/prometheus.yml https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor/grafana/datasources/prometheus.yml
            
            # Pull the latest Docker image
            docker pull itsam77/swiss-be-final:latest
            
            # Stop existing monitoring containers (keep volumes for data persistence)
            docker-compose -f docker-compose.yml down || true
            
            # Clean up only dangling containers (preserve volumes)
            docker container prune -f || true
            
            # Verify directory structure exists
            ls -la monitor/
            
            # Set proper permissions for config files
            chmod 644 monitor/prometheus.yml
            chmod 644 monitor/grafana/datasources/prometheus.yml
            
            # Verify files are regular files, not directories
            file monitor/prometheus.yml
            file monitor/grafana/datasources/prometheus.yml
            
            # Ensure Grafana data directory has proper permissions
            docker volume inspect grafana_data >/dev/null 2>&1 || docker volume create grafana_data
            
            # Start monitoring services
            docker-compose -f docker-compose.yml up -d
            
            # Wait a moment for containers to initialize
            sleep 15
            
            # Check if Prometheus container failed to start and restart if needed
            if ! docker ps | grep -q "prometheus1.*Up"; then
              echo "Prometheus container not running, checking logs and restarting..."
              docker logs prometheus1 || true
              docker-compose -f docker-compose.yml restart prometheus || true
              sleep 5
            fi
            
            # Show running containers status
            docker-compose -f docker-compose.yml ps
            
            # Show logs for any failed containers
            docker-compose -f docker-compose.yml logs --tail=20
        