name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

env:
  DEPLOY_PATH: /root/UPancasila/77maStI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy Monitoring to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Navigate to deployment directory
            cd ${{ env.DEPLOY_PATH }}
            
            # Create monitoring directory if it doesn't exist
            mkdir -p monitoring
            cd monitoring
            
            # Create environment file for the application
            cat > .env <<EOF
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF
            
            # Set proper permissions for env file
            chmod 600 .env
            
            # Create monitor directory if it doesn't exist
            mkdir -p monitor
            cd monitor
            
            # Pull monitoring configuration files
            curl -o docker-compose.yml https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/docker-compose.yml
            curl -o monitor/prometheus.yml https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor/prometheus.yml
            
            # Create monitor-source directory and pull files
            mkdir -p monitor-source
            curl -o monitor-source/collector.py https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor-source/collector.py
            curl -o monitor-source/metrics.py https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor-source/metrics.py
            
            # Create grafana directory structure
            mkdir -p monitor/grafana/datasources
            curl -o monitor/grafana/datasources/prometheus.yml https://raw.githubusercontent.com/ItSam77/Swisstination-BEs/main/monitor/grafana/datasources/prometheus.yml
            
            # Pull the latest Docker image
            docker pull itsam77/swiss-be-final:latest
            
            # Stop existing monitoring containers
            docker-compose -f docker-compose.yml down || true
            
            # Start monitoring services
            docker-compose -f docker-compose.yml up -d
            
            # Show running containers status
            docker-compose -f docker-compose.yml ps
        